### PR TITLE
Management Entity module

### PR DESCRIPTION
**Pull request by mathieucarbou**
- Created `management-entity` module, which will use the `management-registry` module to expose management metadata from clients to TMS by going through the server monitoring service

- Removed enum `MessageType`, which should not be used (message types are not finite)

- Moves all model classes into a `.model` package to avoid package conflict with other management modules

- Added `ClientIdentifier` that can now be used client-side to create a client identifier

- Moved all management modules into the same groupId: `org.terracotta.management`

This PR is required by other PR in Ehcache3 and other projects

### CODE REVIEW

**Comment by anthonydahanne** [comment]
cloudbees does not look happy, is it because of the change of group id ?

**Comment by mathieucarbou** [comment]
I don't know... All was fine on my computer... I'll check...

**Comment by mathieucarbou** [comment]
@anthonydahanne : you are right, it was because I had in my local maven repo the old groupIds, and I forgot to change them in some poms.

**Comment by mathieucarbou** [comment]
test this please

**Comment by mathieucarbou** [comment]
test this please

**Comment by mathieucarbou** [comment]
@anthonydahanne : other issue now, cloudbee cannot find the snapshot repo when the voltron-proxy module is. So I added the repository section in the pom, like in terracotta-platform

**Comment by mathieucarbou** [comment]
👍

**Comment by anthonydahanne** [comment]
LGTM

**Pull request merged**
