### PR TITLE
PR for issues #3, #9, #8, #4, #10, #5

### PR DESCRIPTION
**Pull request by mathieucarbou**
PR for issues #3, #9, #8, #4, #10, #5

### CODE REVIEW

**Comment by mathieucarbou** [comment]
@lorban, @anthonydahanne : I'll let you check / merge it ?

**Comment by lorban** [comment]
If you add AverageHistory and still keep the non-history classes, why not adding a Average class too?

**Comment by lorban** [comment]
Since everything seems to extend from AbstractMeasurableStatistic after your change, why not getting rid of it as well as the MeasurableStatistic interface and merging that all in AbstractStatistic / Statistic?

**Comment by mathieucarbou** [comment]
@lorban , @anthonydahanne : PR updated after review / comments. I added StatisticHistory interface to handle more easily on user side the history-based statistics (having list of samples)

**Pull request merged**
