### PR TITLE
Compat' with Terracotta-OSS/terracotta-platform#68

### PR DESCRIPTION
**Pull request by mathieucarbou**
__Depends on__ Terracotta-OSS/terracotta-platform#68

### CODE REVIEW

**Comment by anthonydahanne** [comment]
cloudbees, test this please

**Comment by mathieucarbou** [comment]
test this please

**Comment by anthonydahanne** [comment]
no not yet ! merge and sync have not finished running yet !

**Comment by anthonydahanne** [comment]
this time should be good ! test this please

**Pull request merged**
